### ISSUE TITLE
Could you please figure out what's going on of this code? gsv_points = ss.identify_gsv_locations(grids)

### ISSUE THREAD

**Issue by Chungleuk** [yonghah/streetscape#2]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in _ensure_valid_index(self, value)
   3423             try:
-> 3424                 value = Series(value)
   3425             except (ValueError, NotImplementedError, TypeError):

/usr/local/lib/python3.6/dist-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    263 
--> 264                 data = SingleBlockManager(data, index, fastpath=True)
    265 

/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py in __init__(self, block, axis, do_integrity_check, fastpath)
   1480         if not isinstance(block, Block):
-> 1481             block = make_block(block, placement=slice(0, len(axis)), ndim=1)
   1482 

/usr/local/lib/python3.6/dist-packages/pandas/core/internals/blocks.py in make_block(values, placement, klass, ndim, dtype, fastpath)
   3094 
-> 3095     return klass(values, ndim=ndim, placement=placement)
   3096 

/usr/local/lib/python3.6/dist-packages/pandas/core/internals/blocks.py in __init__(self, values, placement, ndim)
   2630         super(ObjectBlock, self).__init__(values, ndim=ndim,
-> 2631                                           placement=placement)
   2632 

/usr/local/lib/python3.6/dist-packages/pandas/core/internals/blocks.py in __init__(self, values, placement, ndim)
     86                 'Wrong number of items passed {val}, placement implies '
---> 87                 '{mgr}'.format(val=len(self.values), mgr=len(self.mgr_locs)))
     88 

ValueError: Wrong number of items passed 2, placement implies 0

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-31-7b41473397b2> in <module>()
----> 1 get_ipython().run_cell_magic('time', '', 'gsv_points = ss.identify_gsv_locations(grids)')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2115             magic_arg_s = self.var_expand(line, stack_depth)
   2116             with self.builtin_trap:
-> 2117                 result = fn(magic_arg_s, cell)
   2118             return result
   2119 

</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-60> in time(self, line, cell, local_ns)

/usr/local/lib/python3.6/dist-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/usr/local/lib/python3.6/dist-packages/IPython/core/magics/execution.py in time(self, line, cell, local_ns)
   1191         else:
   1192             st = clock2()
-> 1193             exec(code, glob, local_ns)
   1194             end = clock2()
   1195             out = None

<timed exec> in <module>()

/usr/local/lib/python3.6/dist-packages/streetscape/core.py in identify_gsv_locations(grid_gdf, max_conn, max_sem, timeout)
     94     res_df['geometry']  = res_df.apply(
     95         lambda r: Point(r['location']['lng'], r['location']['lat']),
---> 96         axis=1)
     97     res_df = res_df.drop_duplicates(subset="pano_id").reset_index()
     98     res_df = gpd.GeoDataFrame(res_df).drop(columns=['location'])

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in __setitem__(self, key, value)
   3368         else:
   3369             # set column
-> 3370             self._set_item(key, value)
   3371 
   3372     def _setitem_slice(self, key, value):

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in _set_item(self, key, value)
   3442         """
   3443 
-> 3444         self._ensure_valid_index(value)
   3445         value = self._sanitize_column(key, value)
   3446         NDFrame._set_item(self, key, value)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in _ensure_valid_index(self, value)
   3424                 value = Series(value)
   3425             except (ValueError, NotImplementedError, TypeError):
-> 3426                 raise ValueError('Cannot set a frame with no defined index '
   3427                                  'and a value that cannot be converted to a '
   3428                                  'Series')

ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

**Comment by yonghah** [comment]
Hi Chungleuk!
Can you give me more detail on when you got such an error?
It would be also helpful if you include information on your environment.

**Comment by Chungleuk** [comment]
> Hi Chungleuk!
> Can you give me more detail on when you got such an error?
> It would be also helpful if you include information on your environment.
Hi Yonghah,
Thanks for your kindly reply, at the beginning, I try to set up a virtual environment on my windows 10, however it encounter many errors since I am not pretty well with environment setup.  Then I deploy your example.ipynb on google colab:
https://colab.research.google.com/drive/13OJuSO3BSvo8ACJEdYvBBsp0-A7By6HL

The above error messages was shown in colab. would be grateful if you could advise how to solve this issue, thanks in advance!

**Comment by yonghah** [comment]
Oh I see..Windows 10. I've heard that installing Geopandas in Windows 10 is sometimes not easy. There're two workaround. 

1) Try this in WSL (Windows Subsystem for Linux), which enables you to run Linux on Windows 10 (https://docs.microsoft.com/en-us/windows/wsl/install-win10)

2) Create a virtual environment in conda and use conda-forge for installing dependent libraries. For example
```
conda install -c conda-forge geopandas
```

**Comment by Chungleuk** [comment]
> Oh I see..Windows 10. I've heard that installing Geopandas in Windows 10 is sometimes not easy. There're two workaround.
> 
> 1. Try this in WSL (Windows Subsystem for Linux), which enables you to run Linux on Windows 10 (https://docs.microsoft.com/en-us/windows/wsl/install-win10)
> 2. Create a virtual environment in conda and use conda-forge for installing dependent libraries. For example
> 
> ```
> conda install -c conda-forge geopandas
> ```

Thanks a lot! I will try to run it again on a Linux system

**Comment by Chungleuk** [comment]
I still get stuck, my colleague found another way to download the images for use, thanks a lot!

________________________________
寄件者: Yongha Hwang <notifications@github.com>
寄件日期: 2019年3月26日 16:13
收件者: yonghah/streetscape
副本: Lee Chung Leuk; Author
主旨: Re: [yonghah/streetscape] Could you please figure out what's going on of this code? gsv_points = ss.identify_gsv_locations(grids) (#2)


Closed #2<https://github.com/yonghah/streetscape/issues/2>.
